var fs = require('fs');
var xd1 = '"';
var xd2 = '"';
var domain1 = '*.localhost.com';
var domain2 = 'www.localhost.com';
var xmlVersion = '<?xml version="1.0"?>';
var versionWrite = '<!-- This crossdomain.xml is generated using CPLiteServer and created by Zaseth -->';
var breakLine = "\r\n";
var headXml = '<site-control permitted-cross-domain-policies="master-only"/>';
var siteUrl = '<allow-access-from domain=' + xd1 + domain1 + xd2 + " " + 'secure="false"/>';
var siteUrl2 = '<allow-access-from domain=' + xd1 + domain2 + xd2 + " " + 'secure="false"/>';
var siteHeader = '<allow-http-request-headers-from domain=' + xd1 + domain1 + xd2 + " " + 'headers="SOAPAction" secure="false"/>';
var siteHeader2 = '<allow-http-request-headers-from domain=' + xd1 + domain2 + xd2 + " " + 'headers="SOAPAction" secure="false"/>';
var xmlEnd = '</cross-domain-policy>';
var stream = fs.createWriteStream("crossdomain.xml");
console.log('Done');
console.log('Created by Zaseth');
stream.once('open', function(fd) {
  stream.write(xmlVersion);
  stream.write(breakLine);
  stream.write(versionWrite);
  stream.write(breakLine);
  stream.write(headXml);
  stream.write(breakLine);
  stream.write(siteUrl);
  stream.write(breakLine);
  stream.write(siteUrl2);
  stream.write(breakLine);
  stream.write(siteHeader);
  stream.write(breakLine);
  stream.write(siteHeader2);
  stream.write(breakLine);
  stream.write(xmlEnd);
  stream.end();
});
